<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-03-20T13:00:39 IST" name="Regression_Suite" finished-at="2022-03-20T13:01:01 IST" duration-ms="22003">
    <groups>
    </groups>
    <test started-at="2022-03-20T13:00:39 IST" name="Test case 1" finished-at="2022-03-20T13:01:01 IST" duration-ms="22003">
      <class name="com.selenium.testcase_fd.Fixeddeposite_test">
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:com.selenium.testcase_fd.Fixeddeposite_test@57d7f8ca]" started-at="2022-03-20T13:00:39 IST" name="beforeTest" finished-at="2022-03-20T13:00:43 IST" duration-ms="4001" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method signature="fixeddeposite_1lakh()[pri:0, instance:com.selenium.testcase_fd.Fixeddeposite_test@57d7f8ca]" started-at="2022-03-20T13:00:43 IST" name="fixeddeposite_1lakh" description="Test case to verify Fixed Deposit module for 1 lakhs" finished-at="2022-03-20T13:00:51 IST" duration-ms="7335" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fixeddeposite_1lakh -->
        <test-method signature="fixeddeposite_2lakh()[pri:1, instance:com.selenium.testcase_fd.Fixeddeposite_test@57d7f8ca]" started-at="2022-03-20T13:00:51 IST" name="fixeddeposite_2lakh" description="Test case to verify Fixed Deposit module for 2 lakhs" finished-at="2022-03-20T13:00:55 IST" duration-ms="4005" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fixeddeposite_2lakh -->
        <test-method signature="fixeddeposite_3lakh()[pri:2, instance:com.selenium.testcase_fd.Fixeddeposite_test@57d7f8ca]" started-at="2022-03-20T13:00:56 IST" name="fixeddeposite_3lakh" description="Test case to verify Fixed Deposit module for 3 lakhs" finished-at="2022-03-20T13:01:01 IST" duration-ms="4857" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [396000.00] but found [354000.00]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [396000.00] but found [354000.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.selenium.testcase_fd.Fixeddeposite_test.fixeddeposite_3lakh(Fixeddeposite_test.java:93)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fixeddeposite_3lakh -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:com.selenium.testcase_fd.Fixeddeposite_test@57d7f8ca]" started-at="2022-03-20T13:01:01 IST" name="afterTest" finished-at="2022-03-20T13:01:01 IST" duration-ms="231" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.selenium.testcase_fd.Fixeddeposite_test -->
    </test> <!-- Test case 1 -->
  </suite> <!-- Regression_Suite -->
</testng-results>
